### ISSUE TITLE
[Mobile] XamlMergeOutputFile is not generated when building the app

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno.xamlmerge.task#111]
## Current behavior

When building the app, the XamlMergeOutputFile is not generated.

## Expected behavior

When building the app, the XamlMergeOutputFile should be generated.

## How to reproduce it (as minimally and precisely as possible)

I am working on a net6 uno sample app

## Environment

Nuget Package: uno.winui 4.6.39

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: 17.4.3)

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The only way to generate the file is to rebuild the whole project every time. Simply building does not generate the file. This is causing 2 issues.
- The generated file is not refreshed when only the styles are modified
- The generated file is not found when someone opens the project on the first time making the build fail. It also makes the pipeline fail every time unless you add this file to your solution (I would rather ignore those changes).

**Comment by kazo0** [comment]
@Guidemarcus does it work if you don't define the XamlMergeOutputFile? It should default to Generated/mergedpages.xaml

If it's building only when building the whole solution, maybe the XamlMerge targets aren't being included properly in the project. Are there conditions set on any of the ItemGroups or PropertyGroups that are relevant to XamlMerge? It may get skipped if the conditions don't match the target frameworks for net6.0

**Comment by jeromelaban** [comment]
Can you also [provide a binlog](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) of the build that fails ?

**Comment by Guidemarcus** [comment]
@kazo0 Even without defining the XamlMergeOutputFile, I get the same error.

@jeromelaban We are currently working on a repro. We will also provide a binlog shortly

**Comment by Guidemarcus** [comment]
Here is the binlog file! I had issues uploading it. I had to put it in a zip folder
[binlog.zip](https://github.com/unoplatform/uno.xamlmerge.task/files/10393535/binlog.zip)

**Comment by Guidemarcus** [comment]
Here is the binlog. I added it in a private discussion because of some sensitive information https://github.com/unoplatform/nventive-private/discussions/443
