### ISSUE TITLE
Theme dictionary keys are not correct when merged

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno.xamlmerge.task#29]
## Current behavior

I have a ResourceDictionary with two theme ResourceDictionaries for Light and Dark.  When merged, the Dark one's key is now Default.

Original dictionary:
![image](https://user-images.githubusercontent.com/67480815/149379053-71d15c3b-75a7-4711-ad4f-a64a6c8cbc8f.png)

Merged:
![image](https://user-images.githubusercontent.com/67480815/149379124-488f3754-8602-4629-a68c-13a99615338c.png)

## Expected behavior

Dictionary keys remain the same.

## Environment

Nuget Package: Uno.XamlMerge.Task

Package Version(s): 0.1.0-dev.50

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! In practice, `Default` is an alias for `Dark`, so it does not change the actual behavior. If you see a runtime issue related to this, let us know.
