### ISSUE TITLE
Error .NET6 Class Library

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/uno.xamlmerge.task#92]
## Current behavior

Xaml Merge is working fine in the UWP & Xamarin Class Library but not in the WinUI & MAUI one and almost using the same project config.

It's generating a good file but is giving me the following error:

CSC : error UXAML0001: Processing failed for file C:\P\Nventive.View\src\View.Uno.WinUI\Themes\MergedResourceDictionaries.xaml (System.InvalidOperationException: The type u:DelayControl could not be found

If I ignore the delay control file, it will pass on the error to the next control in the generated file.

## Expected behavior

Xaml Merge should be working in WinUI & MAUI Class Library.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/nventive/Nventive.View/pull/56

https://github.com/nventive/Nventive.View/tree/dev/thla/feat-add-samples

## Environment

Nuget Package:

Package Version(s):

1.1.0-dev.13

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Does this type actually exist in your original content? It may also be that the `u:` namespace is duplicated.

**Comment by Soap-141** [comment]
Found the issue, wrong #if WINDOWS / WINUI tag was being used, currently working on it.
